export const ROUTE_PATHS = {
  LOGIN: '/login',

  JOURNEY_OVERVIEW: '/journey/overview',
  JOURNEY_START: '/journey/start',
  JOURNEY_REVIEW: '/journey/review',
  JOURNEY_RENEWAL: '/journey/renewal',
  JOURNEY_RESULT: '/journey/result',
  JOURNEY_TASKS: '/journey/tasks',
  JOURNEY_AGREEMENT: '/journey/agreement',
  HEALTH_CHECK: '/journey/health-check',
  MY_ELDERS: '/journey/my-elders',
  FAMILY_VISIT_CREATE: '/journey/family-visit/create',
  FAMILY_VISIT_MY: '/journey/family-visit/my',
  CAREGIVER_DAILY_TASKS: '/journey/care-delivery/my-tasks',
  CAREGIVER_CHECK_IN_HISTORY: '/journey/care-delivery/my-check-ins',
  FAMILY_SERVICE_PLANS: '/journey/family/service-plans',
  FAMILY_CHECK_IN_RECORDS: '/journey/family/check-ins',
  FAMILY_CARE_RECORDS: '/journey/family/care-records',
  CAREGIVER_QUALIFICATION_SUBMIT: '/journey/caregiver-qualification/submit',
  CAREGIVER_QUALIFICATION_STATUS: '/journey/caregiver-qualification/status',
} as const;
