export const ROUTE_PATHS = {
  LOGIN: '/login',

  ADMIN_HOME: '/admin/home',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ADMISSION: '/admin/admission',
  ADMIN_NEEDS_ASSESSMENT: '/admin/needs-assessment',
  ADMIN_HEALTH_CHECK_FORMS: '/admin/health-check-forms',
  ADMIN_HEALTH_ASSESSMENT: '/admin/health-assessment',
  ADMIN_NURSE_CARE_RECORDS: '/admin/nurse-care-records',
  ADMIN_DOCTOR_ROUND_RECORDS: '/admin/doctor-round-records',
  ADMIN_FAMILY_VISIT_REVIEWS: '/admin/family-visit-reviews',
  ADMIN_ELDER_BINDING_REVIEWS: '/admin/elder-binding-reviews',
  ADMIN_CAREGIVER_QUALIFICATION_REVIEWS: '/admin/caregiver-qualification-reviews',
  ADMIN_JOURNEY_TASKS: '/admin/journey-tasks',
  ADMIN_USERS_ANALYTICS: '/admin/users-analytics',
  ADMIN_CARE: '/admin/care',
  ADMIN_OPS: '/admin/ops',
  ADMIN_ALERTS: '/admin/alerts',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_PERMISSIONS: '/admin/permissions',
} as const;
