export const AUTH_LOGIN_PATH = '/auth/login';
export const AUTH_LOGOUT_PATH = '/auth/logout';

export const USER_LIST_PATH = '/api/users';
export const USER_ELDER_BINDING_REQUESTS_PATH = '/api/users/elder-binding-requests';
export const USER_ELDER_BINDING_REQUEST_DETAIL_PATH = (requestId: number) => `/api/users/elder-binding-requests/${requestId}`;
export const USER_ELDER_BINDING_REQUEST_APPROVE_PATH = (requestId: number) => `/api/users/elder-binding-requests/${requestId}/approve`;
export const USER_ELDER_BINDING_REQUEST_REJECT_PATH = (requestId: number) => `/api/users/elder-binding-requests/${requestId}/reject`;
export const USER_ANALYTICS_OVERVIEW_PATH = '/api/users/analytics/overview';
export const USER_DETAIL_PATH = (userId: number) => `/api/users/${userId}`;
export const USER_STATUS_PATH = (userId: number) => `/api/users/${userId}/status`;
export const USER_RESET_PASSWORD_PATH = (userId: number) => `/api/users/${userId}/password/reset`;

export const ROLE_LIST_PATH = '/api/roles';
export const ROLE_WITH_PERMISSIONS_PATH = '/api/roles/with-permissions';
export const ROLE_USER_PATH = (userId: number) => `/api/roles/user/${userId}`;
export const ROLE_ASSIGN_USER_PATH = (userId: number, roleId: number) => `/api/roles/user/${userId}/assign/${roleId}`;
export const ROLE_REMOVE_USER_PATH = (userId: number, roleId: number) => `/api/roles/user/${userId}/remove/${roleId}`;
export const ROLE_ASSIGN_PERMISSION_PATH = (roleId: number, permissionId: number) => `/api/roles/${roleId}/permission/${permissionId}`;
export const ROLE_REMOVE_PERMISSION_PATH = (roleId: number, permissionId: number) => `/api/roles/${roleId}/permission/${permissionId}`;

export const PERMISSION_LIST_PATH = '/api/permissions';
export const PERMISSION_TREE_PATH = '/api/permissions/tree';
export const PERMISSION_BY_ROLE_PATH = (roleId: number) => `/api/permissions/role/${roleId}`;
export const PERMISSION_DETAIL_PATH = (permissionId: number) => `/api/permissions/${permissionId}`;
export const PERMISSION_STATUS_PATH = (permissionId: number) => `/api/permissions/${permissionId}/status`;

export const CARE_JOURNEY_OVERVIEW_PATH = '/care-orchestration/journey-overview';
export const CARE_JOURNEY_START_PATH = '/care-orchestration/journeys/start';
export const CARE_JOURNEY_CONTINUE_PATH = '/care-orchestration/journeys/continue';
export const CARE_JOURNEY_REVIEW_PATH = '/care-orchestration/journeys/review';
export const CARE_JOURNEY_TASKS_PATH = '/care-orchestration/journey-tasks';
export const CARE_JOURNEY_TASK_TIMELINE_PATH = '/care-orchestration/journey-tasks/timeline';
export const CARE_JOURNEY_TASK_OVERVIEW_PATH = '/care-orchestration/journey-tasks/overview';
export const CARE_JOURNEY_TRANSITION_LOGS_BY_APPLICATION_PATH = '/care-orchestration/journey-logs/by-application';
export const CARE_JOURNEY_TRANSITION_LOGS_BY_AGREEMENT_PATH = '/care-orchestration/journey-logs/by-agreement';
export const CARE_JOURNEY_RETURN_PATH = '/care-orchestration/journeys/return';

export const ADMISSION_SCOPE_PATH = '/admission/module-scope';
export const ADMISSION_APPLICATIONS_PATH = '/admission/applications';
export const ADMISSION_ASSESSMENTS_PATH = '/admission/assessments';
export const ADMISSION_FAMILY_VISIT_SLOTS_PATH = '/admission/family-visit-slots';
export const ADMISSION_FAMILY_VISIT_RESERVATIONS_PATH = '/admission/family-visit-reservations';
export const ADMISSION_FAMILY_VISIT_RESERVATION_DETAIL_PATH = (reservationId: number) => `/admission/family-visit-reservations/${reservationId}`;
export const ADMISSION_FAMILY_VISIT_RESERVATION_APPROVE_PATH = (reservationId: number) => `/admission/family-visit-reservations/${reservationId}/approve`;
export const ADMISSION_FAMILY_VISIT_RESERVATION_REJECT_PATH = (reservationId: number) => `/admission/family-visit-reservations/${reservationId}/reject`;
export const CONTRACT_SCOPE_PATH = '/contract/module-scope';
export const CONTRACT_AGREEMENT_BY_APPLICATION_PATH = (applicationId: number) =>
  `/contract/agreements/by-application/${applicationId}`;
export const CONTRACT_DRAFT_AGREEMENT_PATH = '/contract/agreements/draft';
export const HEALTH_SCOPE_PATH = '/health/module-scope';
export const ADMIN_HEALTH_CHECK_FORMS_PATH = '/health/admin/check-forms';
export const ADMIN_HEALTH_CHECK_FORM_DETAIL_PATH = (formId: number) => `/health/admin/check-forms/${formId}`;
export const ADMIN_HEALTH_CHECK_FORM_LATEST_PATH = '/health/admin/check-forms/latest';
export const HEALTH_CHECK_FORMS_PATH = '/health/check-forms';
export const HEALTH_CHECK_FORM_DETAIL_PATH = (formId: number) => `/health/check-forms/${formId}`;
export const HEALTH_CHECK_FORM_LATEST_PATH = '/health/check-forms/latest';
export const HEALTH_ASSESSMENT_REQUESTS_PENDING_PATH = '/health/assessment-requests/pending';
export const HEALTH_ASSESSMENT_REQUESTS_HISTORY_PATH = '/health/assessment-requests/history';
export const HEALTH_ASSESSMENT_REQUESTS_PATH = '/health/assessment-requests';
export const HEALTH_DOCTOR_ROUND_RECORDS_PATH = '/health/doctor-round-records';
export const HEALTH_DOCTOR_ROUND_RECORD_DETAIL_PATH = (recordId: number) => `/health/doctor-round-records/${recordId}`;
export const CARE_DELIVERY_SCOPE_PATH = '/care-delivery/module-scope';
export const CARE_DELIVERY_NURSE_CARE_RECORDS_PATH = '/care-delivery/nurse-care-records';
export const CARE_DELIVERY_NURSE_CARE_RECORD_DETAIL_PATH = (recordId: number) => `/care-delivery/nurse-care-records/${recordId}`;
export const QUALITY_SCOPE_PATH = '/quality/module-scope';
export const QUALITY_CAREGIVER_QUALIFICATION_APPLICATIONS_PATH = '/quality/caregiver-qualification-applications';
export const QUALITY_CAREGIVER_QUALIFICATION_APPLICATION_DETAIL_PATH = (applicationId: number) => `/quality/caregiver-qualification-applications/${applicationId}`;
export const QUALITY_CAREGIVER_QUALIFICATION_APPLICATION_APPROVE_PATH = (applicationId: number) => `/quality/caregiver-qualification-applications/${applicationId}/approve`;
export const QUALITY_CAREGIVER_QUALIFICATION_APPLICATION_REJECT_PATH = (applicationId: number) => `/quality/caregiver-qualification-applications/${applicationId}/reject`;
export const BILLING_SCOPE_PATH = '/billing/module-scope';
export const RESOURCE_SCHEDULING_SCOPE_PATH = '/resource-scheduling/module-scope';
export const SAFETY_EMERGENCY_SCOPE_PATH = '/safety-emergency/module-scope';
export const OPS_BUSINESS_INFO_PATH = '/business/info';
export const CARE_ANALYTICS_OVERVIEW_PATH = '/care-orchestration/analytics/overview';
export const CARE_ANALYTICS_TRENDS_PATH = '/care-orchestration/analytics/trends';
